#ifndef EXPANSE_CLOUD_GLOBALS_INCLUDED
#define EXPANSE_CLOUD_GLOBALS_INCLUDED

#include "UniversalCloudLayer.cs.hlsl"

StructuredBuffer<UniversalCloudLayerRenderSettings> _ExpanseCloudLayers;
StructuredBuffer<UniversalCloudNoiseLayerRenderSettings> _ExpanseCloudNoises;
int _ExpanseNumCloudLayers;

#endif // EXPANSE_CLOUD_GLOBALS_INCLUDED